# This is YAML code that defines Github Actions workflow that automatically runs Python tests whenever code is pushed or pulled 
# to a repo, so not to break existing code.

#It's a part of CI part of DevOps practices.


name: Python Tests # name of the workflow in Github Actions Tab.

on: # to specify events that will trigger the workflow
  - push
  - pull_request


# A job is a sequence of steps that run on a single virtual machine.
# Here we define a single job called "test" that runs on the latest version of Ubuntu 
jobs:
    test: #(name of the job)
        runs-on: ubuntu-latest # the virtual machine that this job will run on, provided by Github so that we don't manage our own hardware/servers.

        steps: # a list of commands that are executed sequentially within the test job.
            - name: Checkout repository # name of the step
              uses: actions/checkout@v3 # this step uses a pre-build action from github that downloads the repository's code on the virtual machine/runner.
            
            - name: Set up Python
              uses: actions/setup-python@v4 # another pre-built action to set up a specific version of Python on the virtual machine.
              with: # parameters for the setup-python action
                python-version: '3.13' # specify the version of Python to be installed.
            
            - name: Install dependencies
              run: | # run allows us to execute commands on the virtual machine.
                python -m pip install --upgrade pip 
                pip install pytest

            - name: Run pytests
              run: |
                pytest -v --junitxml=report.xml

            - name: Uploading test report # this step uploads the test report generated by pytest as an artifact to the workflow run.
              uses: actions/upload-artifact@v4
              with:
                name: test-report
                path: report.xml
                retention-days: 30